In [ ]:
import re
import pandas as pd

In [ ]:
f = open('WhatsApp Chat with Discussion Group.txt','r',encoding = 'utf-8')

In [ ]:
data = f.read()

In [ ]:
print(data)

8/15/25, 3:44 PM - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*.
7/2/25, 2:15 PM - ~ aqsa45476 created group "No tension aish kro"
7/2/25, 2:15 PM - You were added
8/15/25, 8:53 PM - +92 328 2954199: This message was deleted
8/15/25, 8:55 PM - Hamza Memon Uni Cf: <Media omitted>
8/15/25, 8:56 PM - humbal Uni CF: Oh bhai zinda hun me czn ne kia hai story upload to iss ne grp me send krdi
8/19/25, 12:17 AM - +92 302 0216782: Transcript kb tk Aaye gii
8/19/25, 12:17 AM - Saher Uni CF: Jub ayegi mein Bata dongi
8/19/25, 12:17 AM - +92 334 2169768: This message was deleted
8/19/25, 12:17 AM - Ayan Uni Cf: <Media omitted>
8/19/25, 12:17 AM - +92 302 0216782: Ok 👍🏻
8/19/25, 12:17 AM - +92 334 2169768: mis click
8/19/25, 12:17 AM - +92 302 0216782: Hm hm ok
8/19/25, 12:18 AM - Saher Uni CF: This message was deleted
8/19/25, 12:19 AM - Mudassir Uni Cf: This message was deleted
8/19/25, 12:19 AM - +92 334 2169768: 🤦🏻
8/19/25, 12:19 AM - Saher Uni CF: This message was deleted
8/19/25, 12:19 AM - Ayan Uni Cf: Heavy 😂
8/19/25, 12:20 AM - Ayan Uni Cf: <Media omitted>
8/19/25, 12:20 AM - +92 312 1154543: <Media omitted>
8/19/25, 12:20 AM - +92 312 1154543: <Media omitted>
8/19/25, 12:20 AM - Ayan Uni Cf: Astagfirullah mein jarha hoon
8/19/25, 12:20 AM - Mudassir Uni Cf: Ohh mjhy Laga ... Acha choren
8/19/25, 12:20 AM - +92 334 2169768: agree
8/19/25, 12:20 AM - +92 302 0216782: Sojao
Rat hogai
8/19/25, 12:21 AM - +92 312 1154543: Hn to jayaiii
8/19/25, 12:21 AM - Ayan Uni Cf: Apse poucha mene 😎
8/19/25, 12:21 AM - +92 334 2169768: thank u for a such rare info
ap bhi 🙂
8/19/25, 12:21 AM - +92 302 0216782: Apsy nhi bola 🙂
8/19/25, 12:21 AM - Ayan Uni Cf: Bro code followed brilliantly 🫂
8/19/25, 12:22 AM - +92 318 0201414: Group wale zinda Hain 🤨
8/19/25, 12:22 AM - Ayan Uni Cf: Hn wo bss galati se aj ammi ne mara nhi hai kisi ko isliye
8/19/25, 12:22 AM - +92 334 2169768: tw phir kis sy bola
q k apsy tw koi batt hi nhi kar Raha
8/19/25, 12:23 AM - +92 334 2169768: khair ..... i give up
8/19/25, 12:23 AM - +92 302 0216782: Meiny apsy to nhi bola na
Ap itna Q bolty ho
8/19/25, 12:23 AM - +92 312 1154543: Apko btaya mai nai?
8/19/25, 12:23 AM - +92 334 2169768: theek hy
8/19/25, 12:23 AM - +92 312 1154543: <Media omitted>
8/19/25, 12:24 AM - Ayan Uni Cf: Sab bol kr give nhi hota hai 😂
8/19/25, 12:24 AM - +92 334 2169768: fazool ma btt barany ki adat nhi hy ab mujhy <This message was edited>
8/19/25, 12:24 AM - Ayan Uni Cf: Ye rare talent kahan se lai ho ap 😂
8/19/25, 12:25 AM - Ayan Uni Cf: Mazrat 🙂
8/19/25, 12:25 AM - +92 312 1154543: Yai tum nai kis ko bola?
8/19/25, 12:25 AM - +92 334 2169768: 🤷🏻
8/19/25, 12:25 AM - Ayan Uni Cf: Hussain bhai ko 😂
8/19/25, 12:26 AM - +92 312 1154543: Pkkka ya PA kai pas jaon?
8/19/25, 12:26 AM - Ayan Uni Cf: Nhi nhi ap wahan na jao pakki bt hai
Mujh na abhi or jeena hai 😂
8/19/25, 12:27 AM - +92 334 2169768: 👀
darpok <This message was edited>
8/19/25, 12:27 AM - +92 312 1154543: <Media omitted>
8/19/25, 12:27 AM - +92 334 2169768: 😮‍💨
8/19/25, 12:28 AM - +92 334 2169768: Allah Hafiz
@⁨+92 302 0216782⁩ kam bola krein
8/19/25, 12:28 AM - +92 302 0216782: Pehly ap Amal karyn
8/19/25, 12:29 AM - Ayan Uni Cf: Aey ja na 😂
8/19/25, 12:30 AM - Ayan Uni Cf: Ya bulaon mein phir.... Iykyk
8/19/25, 12:30 AM - +92 334 2169768: kosish kar raha hun par @⁨+92 302 0216782⁩ ko sukon barbad karny ki adat ha
8/19/25, 12:30 AM - +92 334 2169768: acha khair chorein
buhut hogai fazool batein
8/19/25, 12:31 AM - +92 334 2169768: Allah Hafiz
8/19/25, 12:31 AM - +92 302 0216782: Toba hai Hussain Bhai 🙄
8/19/25, 12:31 AM - +92 334 2169768: just mazaq tha
8/19/25, 12:31 AM - Ayan Uni Cf: I am out
8/19/25, 12:31 AM - Ayan Uni Cf: Allah Hafiz tc berother 🫂
8/19/25, 12:31 AM - +92 334 2169768: This message was deleted
8/19/25, 12:32 AM - Ayan Uni Cf: Mein kehne wala but ab nhi face to face 😂
8/19/25, 12:33 AM - +92 334 2169768: abhi nhi
mujha abhi nhi dekhna apka face
8/19/25, 12:33 AM - +92 334 2169768: i mean ma dekh lon ga
par abhi break hn
8/19/25, 12:33 AM - Ayan Uni Cf: Abhu dekha kom rha hai enrollment wale din milna 😂
8/19/25, 12:33 AM - Ayan Uni Cf: Ofcourse bro ap khayal kro apna abhi 😂
8/19/25, 12:35 AM - +92 334 2169768: donee
8/19/25, 12:35 AM - +92 334 2169768: This message was deleted
8/19/25, 12:36 AM - Ayan Uni Cf: Lagta hau kafi jaldi send delete krne lage ho ap 😂
8/19/25, 12:38 AM - +92 334 2169768: bhai chor dooo
8/19/25, 12:38 AM - Ayan Uni Cf: Okie okie
8/19/25, 12:38 AM - +92 334 2169768: hamara der tk batt karna munasib nhi hyyy
8/19/25, 12:38 AM - +92 334 2169768: iykyk
8/19/25, 12:39 AM - Ayan Uni Cf: Ofcourse 😂
8/22/25, 12:24 PM - +92 313 2183896: <Media omitted>
8/23/25, 3:09 AM - humbal Uni CF: Bhai mujhe to next year ka scene lgraha hai q k mujhe nhi lgta prso wale salab ke baad University ki bnjar deewaren theek honghi🤣
8/23/25, 3:31 PM - +92 303 2676707: <Media omitted>
8/23/25, 3:35 PM - humbal Uni CF: Uhm uhm bs apse thori km krleta hun
8/23/25, 3:36 PM - +92 303 2676707: <Media omitted>
8/23/25, 3:37 PM - humbal Uni CF: <Media omitted>
8/23/25, 3:38 PM - +92 313 2183896: <Media omitted>
8/23/25, 3:45 PM - +92 303 2676707: <Media omitted>
8/23/25, 3:45 PM - +92 313 2183896: <Media omitted>
8/23/25, 3:46 PM - +92 303 2676707: <Media omitted>
8/23/25, 5:35 PM - +92 312 1154543: Hahahahhahahahahh good one
8/23/25, 9:10 PM - Ayan Uni Cf: Husshhh
8/23/25, 9:28 PM - Abdul Hadi: https://www.instagram.com/p/DNr4MbrWDoJ/?igsh=YnFpNjN1bzlrZWU4
8/23/25, 9:40 PM - +92 312 1154543: Ap c bt ki ya ap ko bola ?
8/23/25, 9:55 PM - +92 337 2344777: Hahahah😂😂
8/23/25, 10:02 PM - +92 312 1154543: <Media omitted>
8/23/25, 10:04 PM - Kaleemullah Smiu CF: <Media omitted>
8/23/25, 10:52 PM - Ayan Uni Cf: Tu mein apke kehne ka wait kronga kiya
8/23/25, 10:52 PM - Ayan Uni Cf: 😎
8/23/25, 10:53 PM - Ayan Uni Cf: Hn jao 😂😎
8/23/25, 10:54 PM - +92 312 1154543: Ary bhae jao naaa
8/23/25, 10:55 PM - +92 312 1154543: Ghoom phir kai phr ajatai ho
8/23/25, 10:55 PM - +92 312 1154543: Tum c poch kr jaon gi?
8/23/25, 10:55 PM - Kaleemullah Smiu CF: @⁨Ayan Uni Cf⁩ mein na sehta 😊
8/23/25, 10:56 PM - +92 312 1154543: Yai dheeeet hai naa ab dekhna phr ajain ga
8/23/25, 10:57 PM - Kaleemullah Smiu CF: Sahi baat hai @⁨Ayan Uni Cf⁩ dikh mat jaaiyo. 🙂
8/23/25, 10:57 PM - +92 312 1154543: <Media omitted>
8/23/25, 10:59 PM - Ayan Uni Cf: Kion daar gai ap
8/23/25, 10:59 PM - Ayan Uni Cf: 😎
8/23/25, 11:00 PM - Ayan Uni Cf: Ary jao jao phele tu ap aai teh
8/23/25, 11:00 PM - Ayan Uni Cf: Copy cat 😺😎
8/23/25, 11:00 PM - Ayan Uni Cf: Mein takkar ke logon se larta hoon ustaad kaleem 🫡
8/23/25, 11:00 PM - Ayan Uni Cf: Alhumdullilah 😎
8/23/25, 11:01 PM - Ayan Uni Cf: Ye kisi or dialogue hai ustaad kaleem suit nhi ho rha ap per 🥲
8/23/25, 11:01 PM - Ayan Uni Cf: Haww appi apko alien keh rha hai
8/23/25, 11:01 PM - Kaleemullah Smiu CF: Mat karo takraa kar bikhar jaogy ✨
8/23/25, 11:01 PM - Kaleemullah Smiu CF: Nice try 😂
8/23/25, 11:02 PM - +92 312 1154543: Aur tum c ?
8/23/25, 11:02 PM - +92 312 1154543: Ary bhae
8/23/25, 11:02 PM - Ayan Uni Cf: Kia mtlb ap kia kehna chah rhe ho appi ko 😂
8/23/25, 11:02 PM - +92 312 1154543: Aag mt lagao
8/23/25, 11:02 PM - Ayan Uni Cf: Hn jee 😎
8/23/25, 11:02 PM - Ayan Uni Cf: Hahaha 😂
8/23/25, 11:02 PM - +92 312 1154543: Phr aaag
8/23/25, 11:02 PM - Ayan Uni Cf: Sach hai dekho ap khud
8/23/25, 11:02 PM - Ayan Uni Cf: Ary jao na 😂
8/23/25, 11:03 PM - +92 312 1154543: Tmhari trh farigh ni
8/23/25, 11:03 PM - +92 312 1154543: Ab uper c dabra msg prho
8/23/25, 11:03 PM - Ayan Uni Cf: Look whose talking 👀
8/23/25, 11:03 PM - Ayan Uni Cf: Nhiii
8/23/25, 11:03 PM - +92 312 1154543: 👀
8/23/25, 11:03 PM - Ayan Uni Cf: @⁨~Haseeb Saryal⁩ ap zinda ho
8/23/25, 11:03 PM - Kaleemullah Smiu CF: Nice try again
8/23/25, 11:04 PM - +92 328 2954199: Ayan m bhari mehfil m gaali de doonga aaja wapis
8/23/25, 11:04 PM - +92 303 2676707: <Media omitted>
8/23/25, 11:04 PM - Ayan Uni Cf: Ustaad kaleem kuch naya lao na
8/23/25, 11:04 PM - +92 312 1154543: Ahhaha
8/23/25, 11:04 PM - Ayan Uni Cf: Arha hoon chalooooooo
8/23/25, 11:04 PM - +92 312 1154543: Ap bh ajao
8/23/25, 11:04 PM - Ayan Uni Cf: Ap jao yahan se
8/23/25, 11:04 PM - Kaleemullah Smiu CF: Chal chal avey goodnight 🌝
8/23/25, 11:05 PM - Ayan Uni Cf: <Media omitted>
8/23/25, 11:11 PM - Mubeen Uni CF joined using a group link.
8/24/25, 10:42 AM - Ayan Uni Cf: Second semester ka schedule agaya hai kiya?
8/24/25, 10:49 AM - Saif Uni Cf: Es bar jo entry  test howa hai us ka merit list aaya hai ??
8/24/25, 10:55 AM - +92 302 0216782: Not yet
8/24/25, 11:10 AM - Usman Uni CF: Nahi
8/24/25, 12:26 PM - +92 312 1154543: Bhut jldi hai tmhai
8/24/25, 12:28 PM - Ayan Uni Cf: Ary hn na iykyk 👀😂
8/24/25, 12:36 PM - +92 312 1154543: Hahahha yes yes ik🤣🤣🤣
8/24/25, 12:37 PM - Ayan Uni Cf: Good hogya 😂
8/24/25, 12:38 PM - +92 312 1154543: <Media omitted>
8/24/25, 12:39 PM - Ayan Uni Cf: Ismein bhi iykyk 👀😂
8/24/25, 12:39 PM - +92 312 1154543: Tbh bhja🤣🤣🤣🤣🤣
8/24/25, 12:39 PM - Ayan Uni Cf: Astagfirullah toba toba 😂
8/24/25, 12:40 PM - +92 312 1154543: <Media omitted>
8/24/25, 12:40 PM - +92 312 1154543: Yai zyada suit krta hai ifykyk
8/24/25, 12:40 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 12:40 PM - Ayan Uni Cf: I am out in this 😂
8/24/25, 12:40 PM - +92 312 1154543: Bachaa dr gya
8/24/25, 12:41 PM - Ayan Uni Cf: Kabhu kabhi khamoshi achi cheez hoti hai 😂
8/24/25, 12:41 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 12:41 PM - Ayan Uni Cf: Btw iske bare mein kiya kehna hai iykyk 😂
8/24/25, 12:41 PM - +92 312 1154543: Kbh kbhar khamoshi achi chz hoti hai
8/24/25, 12:42 PM - Ayan Uni Cf: Uno reverse hogya 😂
8/24/25, 12:42 PM - +92 312 1154543: Yeshhhh🤣🤣🤣
8/24/25, 12:42 PM - Ayan Uni Cf: Good 😂
8/24/25, 12:42 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 12:42 PM - +92 312 1154543: Bhae ab chltai bno
8/24/25, 12:43 PM - +92 328 2954199: Dm naam suna h?
8/24/25, 12:43 PM - +92 312 1154543: Ap ko kisi nai bolaya
8/24/25, 12:43 PM - +92 312 1154543: <Media omitted>
8/24/25, 12:43 PM - Ayan Uni Cf: Apse poucha
8/24/25, 12:44 PM - Ayan Uni Cf: Hushhhhh
8/24/25, 12:44 PM - +92 312 1154543: Ary bhae jao na
8/24/25, 12:44 PM - Ayan Uni Cf: BHAAAAP
8/24/25, 12:44 PM - +92 312 1154543: Blah blah
8/24/25, 12:44 PM - +92 328 2954199: Sorry ayan m naam c dhoka khaa gaya
8/24/25, 12:44 PM - +92 312 1154543: Mtlb smjhi ni
8/24/25, 12:45 PM - Ayan Uni Cf: Mein samjh gaya 😂
8/24/25, 12:45 PM - +92 312 1154543: Merko bh smjha
8/24/25, 12:45 PM - Ayan Uni Cf: Ye samjhaiga
8/24/25, 12:45 PM - +92 312 1154543: Smjhao
8/24/25, 12:45 PM - +92 328 2954199: Q bacchon ko pareshan karna ha
8/24/25, 12:45 PM - +92 328 2954199: Akely m pooch lou na
8/24/25, 12:45 PM - Ayan Uni Cf: Hahaha 😂😂
8/24/25, 12:45 PM - Ayan Uni Cf: Appi mein na sehta 😂
8/24/25, 12:45 PM - Ayan Uni Cf: Mein nhi btaonga 😂
8/24/25, 12:45 PM - +92 312 1154543: Jao ayan poch kr ao
8/24/25, 12:46 PM - +92 312 1154543: <Media omitted>
8/24/25, 12:46 PM - Ayan Uni Cf: Apko keh rha hai 😂
8/24/25, 12:46 PM - +92 312 1154543: Bhae asrat ho rhai tum ko bh
8/24/25, 12:46 PM - Ayan Uni Cf: Bro for a reason 😂
8/24/25, 12:46 PM - +92 312 1154543: .............
8/24/25, 12:47 PM - +92 328 2954199: Ayyan ghar ki baat ghar m rehni chaiye
8/24/25, 12:47 PM - +92 312 1154543: Ary jao na bhae dono
8/24/25, 12:47 PM - +92 328 2954199: Gr hou aap group hamara ha
8/24/25, 12:47 PM - +92 312 1154543: Grouo bnaya mai nai hai
8/24/25, 12:47 PM - +92 328 2954199: Jab dil karega jaayengy
8/24/25, 12:48 PM - +92 312 1154543: Achaawwwwww?
8/24/25, 12:48 PM - +92 328 2954199: Yahi aata ha bs
8/24/25, 12:48 PM - +92 312 1154543: Ayan dekh lo
8/24/25, 12:48 PM - +92 312 1154543: Yesh😎
8/24/25, 12:49 PM - +92 328 2954199: This message was deleted
8/24/25, 12:50 PM - +92 312 1154543: <Media omitted>
8/24/25, 12:53 PM - Ayan Uni Cf: Beshak ✨
8/24/25, 12:53 PM - Ayan Uni Cf: Bt tu sahi hai 😂
8/24/25, 12:53 PM - Ayan Uni Cf: Kis ko
8/24/25, 12:54 PM - +92 337 2344777: Aqsa chli gai hai abhi tw ap thora sabr krlein ismein😒
8/24/25, 12:55 PM - Ayan Uni Cf: @⁨~Haseeb Saryal⁩ what is this behavior 👀
8/24/25, 12:55 PM - Ayan Uni Cf: Sab leave krdo haseeb naya group bana rha hai 😂
8/24/25, 12:55 PM - +92 337 2344777: Faida whn bhi aqsa yahi bolegi👀👀
8/24/25, 12:56 PM - +92 328 2954199: Oh i can understand darr ka mahoul ha tag bh mjhy hi kia
8/24/25, 12:57 PM - Ayan Uni Cf: Group check ✅😂
8/24/25, 12:57 PM - +92 337 2344777: Sorryyy😂😂
8/24/25, 12:57 PM - Ayan Uni Cf: Apka karna mein akela kion dekhoon 😂
8/24/25, 12:57 PM - Ayan Uni Cf: Good hogya 😂
8/24/25, 12:58 PM - +92 328 2954199: Group ya Dm?
8/24/25, 12:58 PM - Ayan Uni Cf: Group 😂
8/24/25, 1:25 PM - +92 312 1154543: Apnai bro ko
8/24/25, 1:25 PM - +92 312 1154543: In ko sbr khan
8/24/25, 1:25 PM - +92 312 1154543: Achaawwww?
8/24/25, 1:26 PM - +92 312 1154543: @⁨Ayan Uni Cf⁩ bhutttt ni bol rhai tum
8/24/25, 1:30 PM - +92 337 2344777: Hmm bhaee blkl
8/24/25, 1:43 PM - Abdul Hadi: This message was deleted
8/24/25, 1:51 PM - Ayan Uni Cf: Hn phir thek hai 😂
8/24/25, 1:51 PM - Ayan Uni Cf: Ary tu kon sa mere kehne se sab leàve krdeinge 😂
8/24/25, 1:51 PM - Ayan Uni Cf: Poucha ?
8/24/25, 1:52 PM - +92 337 2344777: Achaawww??
8/24/25, 1:53 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:54 PM - +92 312 1154543: Ary bhae jao na ap
8/24/25, 1:54 PM - +92 312 1154543: Phr ajatai ho ghoom kr
8/24/25, 1:55 PM - Ayan Uni Cf: Haha 😆😆😂
8/24/25, 1:55 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:55 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:55 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:55 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:55 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:55 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:55 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:55 PM - Ayan Uni Cf: Lol 🤣
8/24/25, 1:55 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:55 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:55 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:56 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:57 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:57 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:57 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:57 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:57 PM - Ayan Uni Cf: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 337 2344777: Aqsa bsssss
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:57 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - Ayan Uni Cf: This message was deleted
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - +92 312 1154543: <Media omitted>
8/24/25, 1:58 PM - Ayan Uni Cf: @appi
8/24/25, 1:59 PM - +92 312 1154543: Frmao
8/24/25, 2:00 PM - Ayan Uni Cf: Nothing
8/24/25, 2:00 PM - +92 312 1154543: <Media omitted>
8/25/25, 11:01 PM - Ayan Uni Cf: Transcript slip agai hai kiya?
8/25/25, 11:03 PM - Mubeen Uni CF: Check karlon
8/25/25, 11:04 PM - Ayan Uni Cf: Mene dekha hai mera view my grade update nhi hai abhi
8/25/25, 11:04 PM - Mubeen Uni CF: Ohhgh
8/25/25, 11:17 PM - +92 312 1154543: Hr chz ki bhut jldi hai
8/25/25, 11:17 PM - Ayan Uni Cf: Ary nhi ai evening ke larke ki gpa show ho rhi hai
8/25/25, 11:17 PM - Ayan Uni Cf: Ossne pic bheji teh tbhi poucha
8/25/25, 11:18 PM - +92 312 1154543: Acha acha thk hai ro mat
8/25/25, 11:18 PM - Ayan Uni Cf: Ab sahi hai niklo ab ap
8/25/25, 11:18 PM - +92 312 1154543: <Media omitted>
8/25/25, 11:18 PM - +92 312 1154543: Ary bhae jaooo na
8/25/25, 11:18 PM - +92 312 1154543: <Media omitted>
8/25/25, 11:20 PM - Ayan Uni Cf: Hushhh
8/25/25, 11:20 PM - Ayan Uni Cf: <Media omitted>
8/25/25, 11:20 PM - +92 312 1154543: Blah blah blah
8/25/25, 11:20 PM - Ayan Uni Cf: <Media omitted>
8/25/25, 11:21 PM - Ayan Uni Cf: Yahan nhi kr sakta mein or kuch change of topic 😂
8/25/25, 11:21 PM - +92 312 1154543: @⁨+92 337 2344777⁩
8/25/25, 11:21 PM - Ayan Uni Cf: <Media omitted>
8/25/25, 11:21 PM - +92 312 1154543: Hairan mt ho
8/25/25, 11:22 PM - Ayan Uni Cf: <Media omitted>
8/25/25, 11:22 PM - +92 312 1154543: <Media omitted>
8/25/25, 11:22 PM - +92 312 1154543: <Media omitted>
8/25/25, 11:22 PM - +92 312 1154543: <Media omitted>

In [ ]:
pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}[\s\u202F](?:AM|PM)\s-\s'

In [ ]:
messages = re.split(pattern, data)[1:]
len(messages)

13477

In [ ]:
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*.\n',
 '~\u202faqsa45476 created group "No tension aish kro"\n',
 'You were added\n',
 '+92 328 2954199: This message was deleted\n',
 'Hamza Memon Uni Cf: <Media omitted>\n',
 'humbal Uni CF: Oh bhai zinda hun me czn ne kia hai story upload to iss ne grp me send krdi\n',
 '+92 302 0216782: Transcript kb tk Aaye gii\n',
 'Saher Uni CF: Jub ayegi mein Bata dongi\n',
 '+92 334 2169768: This message was deleted\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 302 0216782: Ok 👍🏻\n',
 '+92 334 2169768: mis click\n',
 '+92 302 0216782: Hm hm ok\n',
 'Saher Uni CF: This message was deleted\n',
 'Mudassir Uni Cf: This message was deleted\n',
 '+92 334 2169768: 🤦🏻\n',
 'Saher Uni CF: This message was deleted\n',
 'Ayan Uni Cf: Heavy 😂\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Astagfirullah mein jarha hoon\n',
 'Mudassir Uni Cf: Ohh mjhy Laga ... Acha choren\n',
 '+92 334 2169768: agree\n',
 '+92 302 0216782: Sojao \nRat hogai\n',
 '+92 312 1154543: Hn to jayaiii\n',
 'Ayan Uni Cf: Apse poucha mene 😎\n',
 '+92 334 2169768: thank u for a such rare info \nap bhi 🙂\n',
 '+92 302 0216782: Apsy nhi bola 🙂\n',
 'Ayan Uni Cf: Bro code followed brilliantly 🫂\n',
 '+92 318 0201414: Group wale zinda Hain 🤨\n',
 'Ayan Uni Cf: Hn wo bss galati se aj ammi ne mara nhi hai kisi ko isliye\n',
 '+92 334 2169768: tw phir kis sy bola\nq k apsy tw koi batt hi nhi kar Raha\n',
 '+92 334 2169768: khair ..... i give up\n',
 '+92 302 0216782: Meiny apsy to nhi bola na \nAp itna Q bolty ho\n',
 '+92 312 1154543: Apko btaya mai nai?\n',
 '+92 334 2169768: theek hy\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Sab bol kr give nhi hota hai 😂\n',
 '+92 334 2169768: fazool ma btt barany ki adat nhi hy ab mujhy <This message was edited>\n',
 'Ayan Uni Cf: Ye rare talent kahan se lai ho ap 😂\n',
 'Ayan Uni Cf: Mazrat 🙂\n',
 '+92 312 1154543: Yai tum nai kis ko bola?\n',
 '+92 334 2169768: 🤷🏻\n',
 'Ayan Uni Cf: Hussain bhai ko 😂\n',
 '+92 312 1154543: Pkkka ya PA kai pas jaon?\n',
 'Ayan Uni Cf: Nhi nhi ap wahan na jao pakki bt hai\nMujh na abhi or jeena hai 😂\n',
 '+92 334 2169768: 👀\ndarpok <This message was edited>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 334 2169768: 😮\u200d💨\n',
 '+92 334 2169768: Allah Hafiz \n@\u2068+92 302 0216782\u2069 kam bola krein\n',
 '+92 302 0216782: Pehly ap Amal karyn\n',
 'Ayan Uni Cf: Aey ja na 😂\n',
 'Ayan Uni Cf: Ya bulaon mein phir.... Iykyk\n',
 '+92 334 2169768: kosish kar raha hun par @\u2068+92 302 0216782\u2069 ko sukon barbad karny ki adat ha\n',
 '+92 334 2169768: acha khair chorein \nbuhut hogai fazool batein\n',
 '+92 334 2169768: Allah Hafiz\n',
 '+92 302 0216782: Toba hai Hussain Bhai 🙄\n',
 '+92 334 2169768: just mazaq tha\n',
 'Ayan Uni Cf: I am out\n',
 'Ayan Uni Cf: Allah Hafiz tc berother 🫂\n',
 '+92 334 2169768: This message was deleted\n',
 'Ayan Uni Cf: Mein kehne wala but ab nhi face to face 😂\n',
 '+92 334 2169768: abhi nhi \nmujha abhi nhi dekhna apka face\n',
 '+92 334 2169768: i mean ma dekh lon ga \npar abhi break hn\n',
 'Ayan Uni Cf: Abhu dekha kom rha hai enrollment wale din milna 😂\n',
 'Ayan Uni Cf: Ofcourse bro ap khayal kro apna abhi 😂\n',
 '+92 334 2169768: donee\n',
 '+92 334 2169768: This message was deleted\n',
 'Ayan Uni Cf: Lagta hau kafi jaldi send delete krne lage ho ap 😂\n',
 '+92 334 2169768: bhai chor dooo\n',
 'Ayan Uni Cf: Okie okie\n',
 '+92 334 2169768: hamara der tk batt karna munasib nhi hyyy\n',
 '+92 334 2169768: iykyk\n',
 'Ayan Uni Cf: Ofcourse 😂\n',
 '+92 313 2183896: <Media omitted>\n',
 'humbal Uni CF: Bhai mujhe to next year ka scene lgraha hai q k mujhe nhi lgta prso wale salab ke baad University ki bnjar deewaren theek honghi🤣\n',
 '+92 303 2676707: <Media omitted>\n',
 'humbal Uni CF: Uhm uhm bs apse thori km krleta hun\n',
 '+92 303 2676707: <Media omitted>\n',
 'humbal Uni CF: <Media omitted>\n',
 '+92 313 2183896: <Media omitted>\n',
 '+92 303 2676707: <Media omitted>\n',
 '+92 313 2183896: <Media omitted>\n',
 '+92 303 2676707: <Media omitted>\n',
 '+92 312 1154543: Hahahahhahahahahh good one\n',
 'Ayan Uni Cf: Husshhh\n',
 'Abdul Hadi: https://www.instagram.com/p/DNr4MbrWDoJ/?igsh=YnFpNjN1bzlrZWU4\n',
 '+92 312 1154543: Ap c bt ki ya ap ko bola ?\n',
 '+92 337 2344777: Hahahah😂😂\n',
 '+92 312 1154543: <Media omitted>\n',
 'Kaleemullah Smiu CF: <Media omitted>\n',
 'Ayan Uni Cf: Tu mein apke kehne ka wait kronga kiya\n',
 'Ayan Uni Cf: 😎\n',
 'Ayan Uni Cf: Hn jao 😂😎\n',
 '+92 312 1154543: Ary bhae jao naaa\n',
 '+92 312 1154543: Ghoom phir kai phr ajatai ho\n',
 '+92 312 1154543: Tum c poch kr jaon gi?\n',
 'Kaleemullah Smiu CF: @\u2068Ayan Uni Cf\u2069 mein na sehta 😊\n',
 '+92 312 1154543: Yai dheeeet hai naa ab dekhna phr ajain ga\n',
 'Kaleemullah Smiu CF: Sahi baat hai @\u2068Ayan Uni Cf\u2069 dikh mat jaaiyo. 🙂\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Kion daar gai ap\n',
 'Ayan Uni Cf: 😎\n',
 'Ayan Uni Cf: Ary jao jao phele tu ap aai teh\n',
 'Ayan Uni Cf: Copy cat 😺😎\n',
 'Ayan Uni Cf: Mein takkar ke logon se larta hoon ustaad kaleem 🫡\n',
 'Ayan Uni Cf: Alhumdullilah 😎\n',
 'Ayan Uni Cf: Ye kisi or dialogue hai ustaad kaleem suit nhi ho rha ap per 🥲\n',
 'Ayan Uni Cf: Haww appi apko alien keh rha hai\n',
 'Kaleemullah Smiu CF: Mat karo takraa kar bikhar jaogy ✨\n',
 'Kaleemullah Smiu CF: Nice try 😂\n',
 '+92 312 1154543: Aur tum c ?\n',
 '+92 312 1154543: Ary bhae\n',
 'Ayan Uni Cf: Kia mtlb ap kia kehna chah rhe ho appi ko 😂\n',
 '+92 312 1154543: Aag mt lagao\n',
 'Ayan Uni Cf: Hn jee 😎\n',
 'Ayan Uni Cf: Hahaha 😂\n',
 '+92 312 1154543: Phr aaag\n',
 'Ayan Uni Cf: Sach hai dekho ap khud\n',
 'Ayan Uni Cf: Ary jao na 😂\n',
 '+92 312 1154543: Tmhari trh farigh ni\n',
 '+92 312 1154543: Ab uper c dabra msg prho\n',
 'Ayan Uni Cf: Look whose talking 👀\n',
 'Ayan Uni Cf: Nhiii\n',
 '+92 312 1154543: 👀\n',
 'Ayan Uni Cf: @\u2068~Haseeb Saryal\u2069 ap zinda ho\n',
 'Kaleemullah Smiu CF: Nice try again\n',
 '+92 328 2954199: Ayan m bhari mehfil m gaali de doonga aaja wapis\n',
 '+92 303 2676707: <Media omitted>\n',
 'Ayan Uni Cf: Ustaad kaleem kuch naya lao na\n',
 '+92 312 1154543: Ahhaha\n',
 'Ayan Uni Cf: Arha hoon chalooooooo\n',
 '+92 312 1154543: Ap bh ajao\n',
 'Ayan Uni Cf: Ap jao yahan se\n',
 'Kaleemullah Smiu CF: Chal chal avey goodnight 🌝\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Mubeen Uni CF joined using a group link.\n',
 'Ayan Uni Cf: Second semester ka schedule agaya hai kiya?\n',
 'Saif Uni Cf: Es bar jo entry  test howa hai us ka merit list aaya hai ??\n',
 '+92 302 0216782: Not yet\n',
 'Usman Uni CF: Nahi\n',
 '+92 312 1154543: Bhut jldi hai tmhai\n',
 'Ayan Uni Cf: Ary hn na iykyk 👀😂\n',
 '+92 312 1154543: Hahahha yes yes ik🤣🤣🤣\n',
 'Ayan Uni Cf: Good hogya 😂\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Ismein bhi iykyk 👀😂\n',
 '+92 312 1154543: Tbh bhja🤣🤣🤣🤣🤣\n',
 'Ayan Uni Cf: Astagfirullah toba toba 😂\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: Yai zyada suit krta hai ifykyk\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: I am out in this 😂\n',
 '+92 312 1154543: Bachaa dr gya\n',
 'Ayan Uni Cf: Kabhu kabhi khamoshi achi cheez hoti hai 😂\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: Btw iske bare mein kiya kehna hai iykyk 😂\n',
 '+92 312 1154543: Kbh kbhar khamoshi achi chz hoti hai\n',
 'Ayan Uni Cf: Uno reverse hogya 😂\n',
 '+92 312 1154543: Yeshhhh🤣🤣🤣\n',
 'Ayan Uni Cf: Good 😂\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: Bhae ab chltai bno\n',
 '+92 328 2954199: Dm naam suna h?\n',
 '+92 312 1154543: Ap ko kisi nai bolaya\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Apse poucha\n',
 'Ayan Uni Cf: Hushhhhh\n',
 '+92 312 1154543: Ary bhae jao na\n',
 'Ayan Uni Cf: BHAAAAP\n',
 '+92 312 1154543: Blah blah\n',
 '+92 328 2954199: Sorry ayan m naam c dhoka khaa gaya\n',
 '+92 312 1154543: Mtlb smjhi ni\n',
 'Ayan Uni Cf: Mein samjh gaya 😂\n',
 '+92 312 1154543: Merko bh smjha\n',
 'Ayan Uni Cf: Ye samjhaiga\n',
 '+92 312 1154543: Smjhao\n',
 '+92 328 2954199: Q bacchon ko pareshan karna ha\n',
 '+92 328 2954199: Akely m pooch lou na\n',
 'Ayan Uni Cf: Hahaha 😂😂\n',
 'Ayan Uni Cf: Appi mein na sehta 😂\n',
 'Ayan Uni Cf: Mein nhi btaonga 😂\n',
 '+92 312 1154543: Jao ayan poch kr ao\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Apko keh rha hai 😂\n',
 '+92 312 1154543: Bhae asrat ho rhai tum ko bh\n',
 'Ayan Uni Cf: Bro for a reason 😂\n',
 '+92 312 1154543: .............\n',
 '+92 328 2954199: Ayyan ghar ki baat ghar m rehni chaiye\n',
 '+92 312 1154543: Ary jao na bhae dono\n',
 '+92 328 2954199: Gr hou aap group hamara ha\n',
 '+92 312 1154543: Grouo bnaya mai nai hai\n',
 '+92 328 2954199: Jab dil karega jaayengy\n',
 '+92 312 1154543: Achaawwwwww?\n',
 '+92 328 2954199: Yahi aata ha bs\n',
 '+92 312 1154543: Ayan dekh lo\n',
 '+92 312 1154543: Yesh😎\n',
 '+92 328 2954199: This message was deleted\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Beshak ✨\n',
 'Ayan Uni Cf: Bt tu sahi hai 😂\n',
 'Ayan Uni Cf: Kis ko\n',
 '+92 337 2344777: Aqsa chli gai hai abhi tw ap thora sabr krlein ismein😒\n',
 'Ayan Uni Cf: @\u2068~Haseeb Saryal\u2069 what is this behavior 👀\n',
 'Ayan Uni Cf: Sab leave krdo haseeb naya group bana rha hai 😂\n',
 '+92 337 2344777: Faida whn bhi aqsa yahi bolegi👀👀\n',
 '+92 328 2954199: Oh i can understand darr ka mahoul ha tag bh mjhy hi kia\n',
 'Ayan Uni Cf: Group check ✅😂\n',
 '+92 337 2344777: Sorryyy😂😂\n',
 'Ayan Uni Cf: Apka karna mein akela kion dekhoon 😂\n',
 'Ayan Uni Cf: Good hogya 😂\n',
 '+92 328 2954199: Group ya Dm?\n',
 'Ayan Uni Cf: Group 😂\n',
 '+92 312 1154543: Apnai bro ko\n',
 '+92 312 1154543: In ko sbr khan\n',
 '+92 312 1154543: Achaawwww?\n',
 '+92 312 1154543: @\u2068Ayan Uni Cf\u2069 bhutttt ni bol rhai tum\n',
 '+92 337 2344777: Hmm bhaee blkl\n',
 'Abdul Hadi: This message was deleted\n',
 'Ayan Uni Cf: Hn phir thek hai 😂\n',
 'Ayan Uni Cf: Ary tu kon sa mere kehne se sab leàve krdeinge 😂\n',
 'Ayan Uni Cf: Poucha ?\n',
 '+92 337 2344777: Achaawww??\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: Ary bhae jao na ap\n',
 '+92 312 1154543: Phr ajatai ho ghoom kr\n',
 'Ayan Uni Cf: Haha 😆😆😂\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Lol 🤣\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 337 2344777: Aqsa bsssss\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: This message was deleted\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: @appi\n',
 '+92 312 1154543: Frmao\n',
 'Ayan Uni Cf: Nothing\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Transcript slip agai hai kiya?\n',
 'Mubeen Uni CF: Check karlon\n',
 'Ayan Uni Cf: Mene dekha hai mera view my grade update nhi hai abhi\n',
 'Mubeen Uni CF: Ohhgh\n',
 '+92 312 1154543: Hr chz ki bhut jldi hai\n',
 'Ayan Uni Cf: Ary nhi ai evening ke larke ki gpa show ho rhi hai\n',
 'Ayan Uni Cf: Ossne pic bheji teh tbhi poucha\n',
 '+92 312 1154543: Acha acha thk hai ro mat\n',
 'Ayan Uni Cf: Ab sahi hai niklo ab ap\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: Ary bhae jaooo na\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Hushhh\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: Blah blah blah\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: Yahan nhi kr sakta mein or kuch change of topic 😂\n',
 '+92 312 1154543: @\u2068+92 337 2344777\u2069\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: Hairan mt ho\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 'Ayan Uni Cf: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Ary jao na 😂\n',
 '+92 312 1154543: Ary bhae chltai bno na\n',
 '+92 312 1154543: Mera group mery mrzi\n',
 '+92 312 1154543: <Media omitted>\n',
 'Ayan Uni Cf: Ary jao jao\n',
 'Ayan Uni Cf: Mein nhi maanta\n',
 '+92 312 1154543: Chlo chlo\n',
 'Ayan Uni Cf: Asad ka bhi group hai ye\n',
 'Ayan Uni Cf: Hussh\n',
 '+92 312 1154543: Asad bhai hai?\n',
 '+92 303 2676707: <Media omitted>\n',
 '+92 312 1154543: Ary ab aisa kro gi?\n',
 'Ayan Uni Cf: Jee hn 😂\n',
 '+92 312 1154543: Lgta ni na\n',
 '+92 312 1154543: Dekhtai ni wo\n',
 'Ayan Uni Cf: @\u2068Asad Uni\u2069 mein na sehta 😂\n',
 '+92 312 1154543: @\u2068~.\u2069\n',
 '+92 303 2676707: Hann\n',
 '+92 303 2676707: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 303 2676707: Private jao\n',
 '+92 312 1154543: Bdla\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 303 2676707: Alelelelele\n',
 '+92 312 1154543: Lol\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'humbal Uni CF: <Media omitted>\n',
 'humbal Uni CF: Bhai ye kia bala hai sticker dealer ko nemonia to nhi hogaya khin\n',
 'Mubeen Uni CF: <Media omitted>\n',
 'Mubeen Uni CF: <Media omitted>\n',
 'Asad Uni: sehlo tohra sa\n',
 'Asad Uni: nhi bhai poori class ka group h\n',
 '+92 312 1154543: Lo ayan 🤣🤣mst krdi asad bhai nai tmhari\n',
 '+92 312 1154543: <Media omitted>\n',
 'Mubeen Uni CF: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Mubeen Uni CF: <Media omitted>\n',
 'Ayan Uni Cf: Asad apne party badal li lagta hai 😂\n',
 'Ayan Uni Cf: Mehsoos ho rha hai thora sa mujh ab 😂\n',
 '+92 312 1154543: Acha hao\n',
 'Mubeen Uni CF: <Media omitted>\n',
 'Ayan Uni Cf: Astagfirullah 😂\n',
 '+92 303 2676707: Transcript check kry mfi nhi arhi but mry bhai ki agyi h\n',
 'Mubeen Uni CF: This message was deleted\n',
 '+92 334 2169768: nhi ae\n',
 '+92 334 2169768: ma ny bhi check kiya hy\n',
 '+92 334 2169768: 😓\n',
 '+92 303 2676707: Assalamualaikum Students,\nThe *fee challans* for *Fall 2025* have been issued. You may download them from the CMS portal.\n',
 '+92 303 2676707: <Media omitted>\n',
 "+92 303 2676707: This video is beneficial for u all in downloading your semester fee for *Fall 2025* voucher let's suppose if u have 6 courses you have to insert 6 if u have 5 courses u have to fill 5\n",
 'humbal Uni CF: Humare 6 hn ya 5\n',
 '+92 312 0982319: How will we get to know how many courses we have??\n',
 '+92 303 2676707: 2 3 days m may be official grp py ajaye list\n',
 '+92 303 2676707: To wait krein 10 sep tk date h\n',
 'humbal Uni CF: Zinda ho sb\n',
 'Usman Uni CF: Ha\n',
 'humbal Uni CF: Q ho zinda 1 semester ke baad bhi\n',
 '+92 302 0216782: Transcript upload hoi ?\n',
 'Usman Uni CF: No\n',
 'Saher Uni CF: Hojaygi bhaee itni bhi kia jaldi hai\n',
 '+92 312 1154543: Hahaha\n',
 'humbal Uni CF: Bhai inho ne 4 saal ki degree ko 1 saal me lena hai samjho zara\n',
 'Saher Uni CF: oOoOO ab samjhi\n',
 '+92 302 0216782: Mujhy dekhni hai transcript kesi hoti hai\n',
 '+92 302 0216782: Kesi dekhti hai\n',
 '+92 302 0216782: 🙂\n',
 'Saher Uni CF: Bhaeee transcript nahi hogi voucher hoga I think\n',
 '+92 302 0216782: Tumhy jb kuch pata NHI hai to bol Q rhi ho\n',
 'Saher Uni CF: Same to u\n',
 '+92 312 1154543: Assalam u alaikum classs\n',
 '+92 312 1154543: Bt sonai\n',
 '+92 302 0216782: Walaikum salam\n',
 'Saher Uni CF: Walikum Assalam\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 '+92 312 1154543: <Media omitted>\n',
 'Saher Uni CF: This message was deleted\n',
 '+92 312 1154543: Ek br phr bol rh ho jis ko clear krna ho sir zeeshan kai pas ja kr khud bt kr kai kai ek br clear kr laina\n',
 'Ayan Uni Cf: Walaikum assalam\n',
 '+92 334 2169768: walakum asalam\n',
 '+92 334 2169768: math 1 or math 2 complimentary para rahy hn ubi wala 🙂🥲\n',
 'Yashfeen Uni CF: Walaikum assalam\n',
 '+92 337 2344777: Waalaikum salam\n',
 '+92 303 2676707: Course enrollment will start from Monday, 8th September 2025 till Saturday, 13th September 2025\n\nClasses will commence from Monday,\xa015th September\xa02025.\n',
 'Agha Uni Cf: Assalamualaikum dosto,\nMeri ek guzarish hai… 💔\nMere dada abu ka inteqal ho gaya hai 😭\n\nMeherbani karke sab ek martaba Surah Fatiha\naur teen martaba Surah Ikhlas parh kar unki maghfirat ki dua zaroor kijiye. 🙏🏻\n\nAllah unki qaber ko roshan kare, unki maghfirat farmaaye aur Jannat-ul-Firdous mein unhe buland maqam ata kare. Aameen 🤲🏻\n',

In [ ]:
dates = re.findall(pattern, data)
dates = [date.replace('\u202f', ' ') for date in dates]
dates

['8/15/25, 3:44 PM - ',
 '7/2/25, 2:15 PM - ',
 '7/2/25, 2:15 PM - ',
 '8/15/25, 8:53 PM - ',
 '8/15/25, 8:55 PM - ',
 '8/15/25, 8:56 PM - ',
 '8/19/25, 12:17 AM - ',
 '8/19/25, 12:17 AM - ',
 '8/19/25, 12:17 AM - ',
 '8/19/25, 12:17 AM - ',
 '8/19/25, 12:17 AM - ',
 '8/19/25, 12:17 AM - ',
 '8/19/25, 12:17 AM - ',
 '8/19/25, 12:18 AM - ',
 '8/19/25, 12:19 AM - ',
 '8/19/25, 12:19 AM - ',
 '8/19/25, 12:19 AM - ',
 '8/19/25, 12:19 AM - ',
 '8/19/25, 12:20 AM - ',
 '8/19/25, 12:20 AM - ',
 '8/19/25, 12:20 AM - ',
 '8/19/25, 12:20 AM - ',
 '8/19/25, 12:20 AM - ',
 '8/19/25, 12:20 AM - ',
 '8/19/25, 12:20 AM - ',
 '8/19/25, 12:21 AM - ',
 '8/19/25, 12:21 AM - ',
 '8/19/25, 12:21 AM - ',
 '8/19/25, 12:21 AM - ',
 '8/19/25, 12:21 AM - ',
 '8/19/25, 12:22 AM - ',
 '8/19/25, 12:22 AM - ',
 '8/19/25, 12:22 AM - ',
 '8/19/25, 12:23 AM - ',
 '8/19/25, 12:23 AM - ',
 '8/19/25, 12:23 AM - ',
 '8/19/25, 12:23 AM - ',
 '8/19/25, 12:23 AM - ',
 '8/19/25, 12:24 AM - ',
 '8/19/25, 12:24 AM - ',
 '8/19/25, 12:24 AM - ',
 '8/19/25, 12:25 AM - ',
 '8/19/25, 12:25 AM - ',
 '8/19/25, 12:25 AM - ',
 '8/19/25, 12:25 AM - ',
 '8/19/25, 12:26 AM - ',
 '8/19/25, 12:26 AM - ',
 '8/19/25, 12:27 AM - ',
 '8/19/25, 12:27 AM - ',
 '8/19/25, 12:27 AM - ',
 '8/19/25, 12:28 AM - ',
 '8/19/25, 12:28 AM - ',
 '8/19/25, 12:29 AM - ',
 '8/19/25, 12:30 AM - ',
 '8/19/25, 12:30 AM - ',
 '8/19/25, 12:30 AM - ',
 '8/19/25, 12:31 AM - ',
 '8/19/25, 12:31 AM - ',
 '8/19/25, 12:31 AM - ',
 '8/19/25, 12:31 AM - ',
 '8/19/25, 12:31 AM - ',
 '8/19/25, 12:31 AM - ',
 '8/19/25, 12:32 AM - ',
 '8/19/25, 12:33 AM - ',
 '8/19/25, 12:33 AM - ',
 '8/19/25, 12:33 AM - ',
 '8/19/25, 12:33 AM - ',
 '8/19/25, 12:35 AM - ',
 '8/19/25, 12:35 AM - ',
 '8/19/25, 12:36 AM - ',
 '8/19/25, 12:38 AM - ',
 '8/19/25, 12:38 AM - ',
 '8/19/25, 12:38 AM - ',
 '8/19/25, 12:38 AM - ',
 '8/19/25, 12:39 AM - ',
 '8/22/25, 12:24 PM - ',
 '8/23/25, 3:09 AM - ',
 '8/23/25, 3:31 PM - ',
 '8/23/25, 3:35 PM - ',
 '8/23/25, 3:36 PM - ',
 '8/23/25, 3:37 PM - ',
 '8/23/25, 3:38 PM - ',
 '8/23/25, 3:45 PM - ',
 '8/23/25, 3:45 PM - ',
 '8/23/25, 3:46 PM - ',
 '8/23/25, 5:35 PM - ',
 '8/23/25, 9:10 PM - ',
 '8/23/25, 9:28 PM - ',
 '8/23/25, 9:40 PM - ',
 '8/23/25, 9:55 PM - ',
 '8/23/25, 10:02 PM - ',
 '8/23/25, 10:04 PM - ',
 '8/23/25, 10:52 PM - ',
 '8/23/25, 10:52 PM - ',
 '8/23/25, 10:53 PM - ',
 '8/23/25, 10:54 PM - ',
 '8/23/25, 10:55 PM - ',
 '8/23/25, 10:55 PM - ',
 '8/23/25, 10:55 PM - ',
 '8/23/25, 10:56 PM - ',
 '8/23/25, 10:57 PM - ',
 '8/23/25, 10:57 PM - ',
 '8/23/25, 10:59 PM - ',
 '8/23/25, 10:59 PM - ',
 '8/23/25, 11:00 PM - ',
 '8/23/25, 11:00 PM - ',
 '8/23/25, 11:00 PM - ',
 '8/23/25, 11:00 PM - ',
 '8/23/25, 11:01 PM - ',
 '8/23/25, 11:01 PM - ',
 '8/23/25, 11:01 PM - ',
 '8/23/25, 11:01 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:02 PM - ',
 '8/23/25, 11:03 PM - ',
 '8/23/25, 11:03 PM - ',
 '8/23/25, 11:03 PM - ',
 '8/23/25, 11:03 PM - ',
 '8/23/25, 11:03 PM - ',
 '8/23/25, 11:03 PM - ',
 '8/23/25, 11:03 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:04 PM - ',
 '8/23/25, 11:05 PM - ',
 '8/23/25, 11:11 PM - ',
 '8/24/25, 10:42 AM - ',
 '8/24/25, 10:49 AM - ',
 '8/24/25, 10:55 AM - ',
 '8/24/25, 11:10 AM - ',
 '8/24/25, 12:26 PM - ',
 '8/24/25, 12:28 PM - ',
 '8/24/25, 12:36 PM - ',
 '8/24/25, 12:37 PM - ',
 '8/24/25, 12:38 PM - ',
 '8/24/25, 12:39 PM - ',
 '8/24/25, 12:39 PM - ',
 '8/24/25, 12:39 PM - ',
 '8/24/25, 12:40 PM - ',
 '8/24/25, 12:40 PM - ',
 '8/24/25, 12:40 PM - ',
 '8/24/25, 12:40 PM - ',
 '8/24/25, 12:40 PM - ',
 '8/24/25, 12:41 PM - ',
 '8/24/25, 12:41 PM - ',
 '8/24/25, 12:41 PM - ',
 '8/24/25, 12:41 PM - ',
 '8/24/25, 12:42 PM - ',
 '8/24/25, 12:42 PM - ',
 '8/24/25, 12:42 PM - ',
 '8/24/25, 12:42 PM - ',
 '8/24/25, 12:42 PM - ',
 '8/24/25, 12:43 PM - ',
 '8/24/25, 12:43 PM - ',
 '8/24/25, 12:43 PM - ',
 '8/24/25, 12:43 PM - ',
 '8/24/25, 12:44 PM - ',
 '8/24/25, 12:44 PM - ',
 '8/24/25, 12:44 PM - ',
 '8/24/25, 12:44 PM - ',
 '8/24/25, 12:44 PM - ',
 '8/24/25, 12:44 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:45 PM - ',
 '8/24/25, 12:46 PM - ',
 '8/24/25, 12:46 PM - ',
 '8/24/25, 12:46 PM - ',
 '8/24/25, 12:46 PM - ',
 '8/24/25, 12:46 PM - ',
 '8/24/25, 12:47 PM - ',
 '8/24/25, 12:47 PM - ',
 '8/24/25, 12:47 PM - ',
 '8/24/25, 12:47 PM - ',
 '8/24/25, 12:47 PM - ',
 '8/24/25, 12:48 PM - ',
 '8/24/25, 12:48 PM - ',
 '8/24/25, 12:48 PM - ',
 '8/24/25, 12:48 PM - ',
 '8/24/25, 12:49 PM - ',
 '8/24/25, 12:50 PM - ',
 '8/24/25, 12:53 PM - ',
 '8/24/25, 12:53 PM - ',
 '8/24/25, 12:53 PM - ',
 '8/24/25, 12:54 PM - ',
 '8/24/25, 12:55 PM - ',
 '8/24/25, 12:55 PM - ',
 '8/24/25, 12:55 PM - ',
 '8/24/25, 12:56 PM - ',
 '8/24/25, 12:57 PM - ',
 '8/24/25, 12:57 PM - ',
 '8/24/25, 12:57 PM - ',
 '8/24/25, 12:57 PM - ',
 '8/24/25, 12:58 PM - ',
 '8/24/25, 12:58 PM - ',
 '8/24/25, 1:25 PM - ',
 '8/24/25, 1:25 PM - ',
 '8/24/25, 1:25 PM - ',
 '8/24/25, 1:26 PM - ',
 '8/24/25, 1:30 PM - ',
 '8/24/25, 1:43 PM - ',
 '8/24/25, 1:51 PM - ',
 '8/24/25, 1:51 PM - ',
 '8/24/25, 1:51 PM - ',
 '8/24/25, 1:52 PM - ',
 '8/24/25, 1:53 PM - ',
 '8/24/25, 1:54 PM - ',
 '8/24/25, 1:54 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:55 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:56 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:57 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:58 PM - ',
 '8/24/25, 1:59 PM - ',
 '8/24/25, 2:00 PM - ',
 '8/24/25, 2:00 PM - ',
 '8/25/25, 11:01 PM - ',
 '8/25/25, 11:03 PM - ',
 '8/25/25, 11:04 PM - ',
 '8/25/25, 11:04 PM - ',
 '8/25/25, 11:17 PM - ',
 '8/25/25, 11:17 PM - ',
 '8/25/25, 11:17 PM - ',
 '8/25/25, 11:18 PM - ',
 '8/25/25, 11:18 PM - ',
 '8/25/25, 11:18 PM - ',
 '8/25/25, 11:18 PM - ',
 '8/25/25, 11:18 PM - ',
 '8/25/25, 11:20 PM - ',
 '8/25/25, 11:20 PM - ',
 '8/25/25, 11:20 PM - ',
 '8/25/25, 11:20 PM - ',
 '8/25/25, 11:21 PM - ',
 '8/25/25, 11:21 PM - ',
 '8/25/25, 11:21 PM - ',
 '8/25/25, 11:21 PM - ',
 '8/25/25, 11:22 PM - ',
 '8/25/25, 11:22 PM - ',
 '8/25/25, 11:22 PM - ',
 '8/25/25, 11:22 PM - ',
 '8/25/25, 11:22 PM - ',
 '8/25/25, 11:23 PM - ',
 '8/25/25, 11:23 PM - ',
 '8/25/25, 11:23 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:24 PM - ',
 '8/25/25, 11:25 PM - ',
 '8/25/25, 11:25 PM - ',
 '8/25/25, 11:25 PM - ',
 '8/25/25, 11:25 PM - ',
 '8/25/25, 11:25 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:26 PM - ',
 '8/25/25, 11:27 PM - ',
 '8/25/25, 11:27 PM - ',
 '8/25/25, 11:27 PM - ',
 '8/25/25, 11:27 PM - ',
 '8/25/25, 11:27 PM - ',
 '8/25/25, 11:27 PM - ',
 '8/25/25, 11:27 PM - ',
 '8/25/25, 11:28 PM - ',
 '8/25/25, 11:37 PM - ',
 '8/25/25, 11:37 PM - ',
 '8/25/25, 11:48 PM - ',
 '8/25/25, 11:49 PM - ',
 '8/25/25, 11:49 PM - ',
 '8/25/25, 11:49 PM - ',
 '8/25/25, 11:50 PM - ',
 '8/25/25, 11:59 PM - ',
 '8/26/25, 12:00 AM - ',
 '8/26/25, 12:38 AM - ',
 '8/26/25, 12:39 AM - ',
 '8/26/25, 12:46 AM - ',
 '8/27/25, 2:16 PM - ',
 '8/27/25, 2:42 PM - ',
 '8/27/25, 3:23 PM - ',
 '8/27/25, 3:27 PM - ',
 '8/27/25, 3:55 PM - ',
 '8/27/25, 3:55 PM - ',
 '8/27/25, 3:55 PM - ',
 '8/27/25, 10:30 PM - ',
 '8/27/25, 10:30 PM - ',
 '8/27/25, 10:34 PM - ',
 '8/27/25, 10:35 PM - ',
 '8/27/25, 10:36 PM - ',
 '8/27/25, 10:36 PM - ',
 '8/27/25, 10:36 PM - ',
 '8/28/25, 7:08 PM - ',
 '8/28/25, 7:09 PM - ',
 '8/28/25, 7:09 PM - ',
 '8/28/25, 7:27 PM - ',
 '8/28/25, 7:30 PM - ',
 '8/28/25, 7:30 PM - ',
 '8/28/25, 7:30 PM - ',
 '8/28/25, 7:36 PM - ',
 '8/28/25, 7:37 PM - ',
 '8/28/25, 7:38 PM - ',
 '8/28/25, 7:38 PM - ',
 '8/28/25, 7:38 PM - ',
 '8/28/25, 7:38 PM - ',
 '8/28/25, 7:39 PM - ',
 '8/28/25, 7:39 PM - ',
 '8/28/25, 7:40 PM - ',
 '8/28/25, 7:41 PM - ',
 '8/28/25, 7:41 PM - ',
 '8/28/25, 7:42 PM - ',
 '8/28/25, 7:42 PM - ',
 '8/28/25, 7:43 PM - ',
 '8/28/25, 7:44 PM - ',
 '8/28/25, 7:45 PM - ',
 '8/28/25, 7:51 PM - ',
 '8/28/25, 8:00 PM - ',
 '8/28/25, 9:00 PM - ',
 '8/28/25, 9:01 PM - ',
 '8/28/25, 9:05 PM - ',
 '8/28/25, 9:21 PM - ',
 '8/28/25, 10:33 PM - ',
 '8/28/25, 10:35 PM - ',
 '8/28/25, 10:36 PM - ',
 '8/28/25, 10:38 PM - ',
 '8/28/25, 10:38 PM - ',
 '8/28/25, 10:39 PM - ',
 '8/28/25, 10:41 PM - ',
 '8/28/25, 10:43 PM - ',
 '8/28/25, 10:44 PM - ',
 '8/28/25, 10:48 PM - ',
 '8/28/25, 10:50 PM - ',
 '8/28/25, 10:50 PM - ',
 '8/28/25, 10:54 PM - ',
 '8/28/25, 10:55 PM - ',
 '8/28/25, 11:00 PM - ',
 '8/28/25, 11:11 PM - ',
 '8/28/25, 11:29 PM - ',
 '8/29/25, 12:09 AM - ',
 '8/29/25, 9:17 AM - ',
 '8/29/25, 9:21 AM - ',
 '8/29/25, 9:25 AM - ',
 '8/29/25, 11:52 AM - ',
 '8/29/25, 1:45 PM - ',
 '8/29/25, 1:48 PM - ',
 '8/29/25, 1:49 PM - ',
 '8/29/25, 1:50 PM - ',
 '8/29/25, 1:54 PM - ',
 '8/29/25, 1:54 PM - ',
 '8/29/25, 2:07 PM - ',
 '8/29/25, 2:19 PM - ',
 '8/29/25, 2:33 PM - ',
 '8/29/25, 2:39 PM - ',
 '8/29/25, 2:39 PM - ',
 '8/29/25, 2:39 PM - ',
 '8/29/25, 2:59 PM - ',
 '8/29/25, 3:04 PM - ',
 '8/29/25, 3:04 PM - ',
 '8/29/25, 3:04 PM - ',
 '8/29/25, 3:05 PM - ',
 '8/29/25, 3:16 PM - ',
 '8/29/25, 3:16 PM - ',
 '8/29/25, 3:16 PM - ',
 '8/29/25, 3:16 PM - ',
 '8/29/25, 3:16 PM - ',
 '8/29/25, 3:16 PM - ',
 '8/29/25, 3:17 PM - ',
 '8/29/25, 3:17 PM - ',
 '8/29/25, 3:17 PM - ',
 '8/29/25, 3:17 PM - ',
 '8/29/25, 3:17 PM - ',
 '8/29/25, 3:17 PM - ',
 '8/29/25, 3:18 PM - ',
 '8/29/25, 3:19 PM - ',
 '8/29/25, 3:19 PM - ',
 '8/29/25, 3:19 PM - ',
 '8/29/25, 3:19 PM - ',
 '8/29/25, 3:20 PM - ',
 '8/29/25, 3:20 PM - ',
 '8/29/25, 3:20 PM - ',
 '8/29/25, 3:20 PM - ',
 '8/29/25, 3:20 PM - ',
 '8/29/25, 3:21 PM - ',
 '8/29/25, 3:22 PM - ',
 '8/29/25, 3:22 PM - ',
 '8/29/25, 3:27 PM - ',
 '8/29/25, 3:31 PM - ',
 '8/29/25, 3:33 PM - ',
 '8/29/25, 3:34 PM - ',
 '8/29/25, 3:34 PM - ',
 '8/29/25, 3:35 PM - ',
 '8/29/25, 3:36 PM - ',
 '8/29/25, 4:41 PM - ',
 '8/29/25, 4:41 PM - ',
 '8/30/25, 10:42 AM - ',
 '8/30/25, 11:11 AM - ',
 '8/30/25, 11:12 AM - ',
 '8/30/25, 11:12 AM - ',
 '8/30/25, 11:16 AM - ',
 '8/30/25, 11:22 AM - ',
 '8/30/25, 11:27 AM - ',
 '8/30/25, 12:05 PM - ',
 '8/31/25, 2:25 PM - ',
 '8/31/25, 3:03 PM - ',
 '8/31/25, 3:03 PM - ',
 '8/31/25, 3:04 PM - ',
 '8/31/25, 3:04 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:05 PM - ',
 '8/31/25, 3:06 PM - ',
 '8/31/25, 3:06 PM - ',
 '8/31/25, 3:06 PM - ',
 '8/31/25, 3:06 PM - ',
 '8/31/25, 3:06 PM - ',
 '8/31/25, 3:06 PM - ',
 '8/31/25, 3:07 PM - ',
 '8/31/25, 3:07 PM - ',
 '8/31/25, 3:07 PM - ',
 '8/31/25, 3:07 PM - ',
 '8/31/25, 3:07 PM - ',
 '8/31/25, 3:08 PM - ',
 '8/31/25, 3:08 PM - ',
 '8/31/25, 3:08 PM - ',
 '8/31/25, 3:08 PM - ',
 '8/31/25, 3:08 PM - ',
 '8/31/25, 3:08 PM - ',
 '8/31/25, 3:08 PM - ',
 '8/31/25, 3:09 PM - ',
 '8/31/25, 3:09 PM - ',
 '8/31/25, 3:09 PM - ',
 '8/31/25, 3:09 PM - ',
 '8/31/25, 3:09 PM - ',
 '8/31/25, 3:10 PM - ',
 '8/31/25, 3:10 PM - ',
 '8/31/25, 3:11 PM - ',
 '8/31/25, 3:11 PM - ',
 '8/31/25, 3:11 PM - ',
 '8/31/25, 3:12 PM - ',
 '8/31/25, 3:12 PM - ',
 '8/31/25, 3:12 PM - ',
 '8/31/25, 3:13 PM - ',
 '8/31/25, 3:13 PM - ',
 '8/31/25, 3:13 PM - ',
 '8/31/25, 3:13 PM - ',
 '8/31/25, 3:14 PM - ',
 '8/31/25, 3:14 PM - ',
 '8/31/25, 3:25 PM - ',
 '8/31/25, 3:25 PM - ',
 '8/31/25, 3:35 PM - ',
 '8/31/25, 3:41 PM - ',
 '8/31/25, 3:59 PM - ',
 '8/31/25, 3:59 PM - ',
 '8/31/25, 4:00 PM - ',
 '8/31/25, 4:03 PM - ',
 '8/31/25, 5:14 PM - ',
 '8/31/25, 9:43 PM - ',
 '8/31/25, 9:43 PM - ',
 '8/31/25, 9:43 PM - ',
 '8/31/25, 9:44 PM - ',
 '8/31/25, 9:44 PM - ',
 '8/31/25, 9:45 PM - ',
 '8/31/25, 9:45 PM - ',
 '8/31/25, 9:46 PM - ',
 '8/31/25, 9:47 PM - ',
 '8/31/25, 9:47 PM - ',
 '8/31/25, 9:47 PM - ',
 '8/31/25, 9:48 PM - ',
 '8/31/25, 9:48 PM - ',
 '8/31/25, 9:48 PM - ',
 '8/31/25, 9:48 PM - ',
 '8/31/25, 9:49 PM - ',
 '8/31/25, 9:49 PM - ',
 '8/31/25, 9:52 PM - ',
 '8/31/25, 9:52 PM - ',
 '8/31/25, 9:58 PM - ',
 '8/31/25, 10:02 PM - ',
 '8/31/25, 10:03 PM - ',
 '8/31/25, 10:07 PM - ',
 '8/31/25, 10:07 PM - ',
 '8/31/25, 10:09 PM - ',
 '8/31/25, 10:38 PM - ',
 '8/31/25, 10:59 PM - ',
 '8/31/25, 11:12 PM - ',
 '9/1/25, 8:57 AM - ',
 '9/1/25, 10:20 AM - ',
 '9/1/25, 10:20 AM - ',
 '9/1/25, 10:20 AM - ',
 '9/1/25, 10:49 AM - ',
 '9/1/25, 11:05 AM - ',
 '9/1/25, 12:47 PM - ',
 '9/1/25, 12:49 PM - ',
 '9/1/25, 12:49 PM - ',
 '9/1/25, 12:50 PM - ',
 '9/1/25, 1:37 PM - ',
 '9/2/25, 12:24 PM - ',
 '9/2/25, 12:25 PM - ',
 '9/2/25, 12:25 PM - ',
 '9/2/25, 12:25 PM - ',
 '9/2/25, 12:25 PM - ',
 '9/2/25, 12:26 PM - ',
 '9/2/25, 12:35 PM - ',
 '9/2/25, 12:39 PM - ',
 '9/2/25, 12:40 PM - ',
 '9/2/25, 12:41 PM - ',
 '9/2/25, 1:03 PM - ',
 '9/2/25, 1:04 PM - ',
 '9/2/25, 1:05 PM - ',
 '9/2/25, 1:06 PM - ',
 '9/2/25, 1:06 PM - ',
 '9/2/25, 1:06 PM - ',
 '9/2/25, 1:06 PM - ',
 '9/2/25, 1:08 PM - ',
 '9/2/25, 1:09 PM - ',
 '9/2/25, 1:09 PM - ',
 '9/2/25, 1:09 PM - ',
 '9/2/25, 1:10 PM - ',
 '9/2/25, 1:14 PM - ',
 '9/2/25, 1:16 PM - ',
 '9/2/25, 1:24 PM - ',
 '9/2/25, 2:19 PM - ',
 '9/2/25, 2:19 PM - ',
 '9/2/25, 3:32 PM - ',
 '9/2/25, 3:33 PM - ',
 '9/2/25, 3:36 PM - ',
 '9/2/25, 3:40 PM - ',
 '9/2/25, 3:42 PM - ',
 '9/2/25, 3:46 PM - ',
 '9/2/25, 3:49 PM - ',
 '9/2/25, 3:49 PM - ',
 '9/2/25, 3:49 PM - ',
 '9/2/25, 3:50 PM - ',
 '9/2/25, 3:50 PM - ',
 '9/2/25, 3:50 PM - ',
 '9/2/25, 3:51 PM - ',
 '9/2/25, 3:53 PM - ',
 '9/2/25, 3:53 PM - ',
 '9/2/25, 3:56 PM - ',
 '9/2/25, 3:59 PM - ',
 '9/2/25, 4:00 PM - ',
 '9/2/25, 4:01 PM - ',
 '9/2/25, 4:01 PM - ',
 '9/2/25, 4:01 PM - ',
 '9/2/25, 4:01 PM - ',
 '9/2/25, 4:02 PM - ',
 '9/2/25, 4:03 PM - ',
 '9/2/25, 4:04 PM - ',
 '9/2/25, 4:08 PM - ',
 '9/2/25, 4:08 PM - ',
 '9/2/25, 4:12 PM - ',
 '9/2/25, 4:29 PM - ',
 '9/2/25, 4:29 PM - ',
 '9/2/25, 4:32 PM - ',
 '9/2/25, 4:32 PM - ',
 '9/2/25, 4:32 PM - ',
 '9/2/25, 4:32 PM - ',
 '9/2/25, 4:33 PM - ',
 '9/2/25, 4:34 PM - ',
 '9/2/25, 4:34 PM - ',
 '9/2/25, 4:34 PM - ',
 '9/2/25, 4:34 PM - ',
 '9/2/25, 4:34 PM - ',
 '9/2/25, 4:34 PM - ',
 '9/2/25, 4:34 PM - ',
 '9/2/25, 4:35 PM - ',
 '9/2/25, 4:35 PM - ',
 '9/2/25, 4:35 PM - ',
 '9/2/25, 4:36 PM - ',
 '9/2/25, 4:36 PM - ',
 '9/2/25, 4:36 PM - ',
 '9/2/25, 4:36 PM - ',
 '9/2/25, 4:37 PM - ',
 '9/2/25, 4:37 PM - ',
 '9/2/25, 4:38 PM - ',
 '9/2/25, 4:38 PM - ',
 '9/2/25, 4:40 PM - ',
 '9/2/25, 4:40 PM - ',
 '9/2/25, 4:41 PM - ',
 '9/2/25, 4:44 PM - ',
 '9/2/25, 4:44 PM - ',
 '9/2/25, 4:44 PM - ',
 '9/2/25, 4:44 PM - ',
 '9/2/25, 4:45 PM - ',
 '9/2/25, 4:45 PM - ',
 '9/2/25, 4:46 PM - ',
 '9/2/25, 4:47 PM - ',
 '9/2/25, 4:52 PM - ',
 '9/2/25, 4:52 PM - ',
 '9/2/25, 4:53 PM - ',
 '9/2/25, 5:18 PM - ',
 '9/2/25, 5:22 PM - ',
 '9/2/25, 5:23 PM - ',
 '9/2/25, 5:24 PM - ',
 '9/2/25, 5:24 PM - ',
 '9/2/25, 5:24 PM - ',
 '9/2/25, 5:25 PM - ',
 '9/2/25, 5:25 PM - ',
 '9/2/25, 5:25 PM - ',
 '9/2/25, 5:25 PM - ',
 '9/2/25, 5:25 PM - ',
 '9/2/25, 5:26 PM - ',
 '9/2/25, 5:42 PM - ',
 '9/2/25, 5:42 PM - ',
 '9/2/25, 5:42 PM - ',
 '9/2/25, 5:42 PM - ',
 '9/2/25, 5:42 PM - ',
 '9/6/25, 11:41 AM - ',
 '9/6/25, 11:41 AM - ',
 '9/6/25, 11:43 AM - ',
 '9/6/25, 11:43 AM - ',
 '9/6/25, 11:44 AM - ',
 '9/6/25, 11:44 AM - ',
 '9/6/25, 11:44 AM - ',
 '9/6/25, 11:44 AM - ',
 '9/6/25, 11:44 AM - ',
 '9/6/25, 11:44 AM - ',
 '9/6/25, 11:54 AM - ',
 '9/6/25, 11:55 AM - ',
 '9/6/25, 11:57 AM - ',
 '9/6/25, 11:57 AM - ',
 '9/6/25, 11:57 AM - ',
 '9/6/25, 12:02 PM - ',
 '9/6/25, 12:02 PM - ',
 '9/6/25, 12:06 PM - ',
 '9/6/25, 12:06 PM - ',
 '9/6/25, 12:39 PM - ',
 '9/6/25, 12:39 PM - ',
 '9/6/25, 12:57 PM - ',
 '9/6/25, 12:57 PM - ',
 '9/6/25, 3:58 PM - ',
 '9/6/25, 3:59 PM - ',
 '9/6/25, 3:59 PM - ',
 '9/6/25, 3:59 PM - ',
 '9/6/25, 4:00 PM - ',
 '9/6/25, 11:13 PM - ',
 '9/6/25, 11:14 PM - ',
 '9/6/25, 11:14 PM - ',
 '9/6/25, 11:14 PM - ',
 '9/6/25, 11:17 PM - ',
 '9/6/25, 11:17 PM - ',
 '9/6/25, 11:18 PM - ',
 '9/6/25, 11:40 PM - ',
 '9/6/25, 11:40 PM - ',
 '9/6/25, 11:57 PM - ',
 '9/6/25, 11:57 PM - ',
 '9/6/25, 11:59 PM - ',
 '9/7/25, 12:00 AM - ',
 '9/7/25, 12:01 AM - ',
 '9/7/25, 12:01 AM - ',
 '9/7/25, 12:01 AM - ',
 '9/7/25, 12:02 AM - ',
 '9/7/25, 12:02 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:03 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:04 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:05 AM - ',
 '9/7/25, 12:06 AM - ',
 '9/7/25, 12:06 AM - ',
 '9/7/25, 12:06 AM - ',
 '9/7/25, 12:06 AM - ',
 '9/7/25, 12:06 AM - ',
 '9/7/25, 12:06 AM - ',
 '9/7/25, 12:06 AM - ',
 '9/7/25, 12:07 AM - ',
 '9/7/25, 12:07 AM - ',
 '9/7/25, 12:08 AM - ',
 '9/7/25, 12:08 AM - ',
 '9/7/25, 12:08 AM - ',
 '9/7/25, 12:08 AM - ',
 '9/7/25, 12:09 AM - ',
 '9/7/25, 12:09 AM - ',
 '9/7/25, 12:09 AM - ',
 '9/7/25, 12:09 AM - ',
 '9/7/25, 12:10 AM - ',
 '9/7/25, 12:10 AM - ',
 '9/7/25, 12:10 AM - ',

In [ ]:
df = pd.DataFrame({'user_message': messages, 'message_date': dates})

In [ ]:
df.head()

                                        user_message         message_date
0  Messages and calls are end-to-end encrypted. O...  8/15/25, 3:44 PM -
1  ~ aqsa45476 created group "No tension aish kro"\n   7/2/25, 2:15 PM -
2                                   You were added\n   7/2/25, 2:15 PM -
3        +92 328 2954199: This message was deleted\n  8/15/25, 8:53 PM -
4              Hamza Memon Uni Cf: <Media omitted>\n  8/15/25, 8:55 PM -

In [ ]:
# convert message_date type
df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %I:%M %p - ')

In [ ]:
df.rename(columns={'message_date': 'date'}, inplace=True)

In [ ]:
users = []
messages = []
for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1:]:  # user name
            users.append(entry[1])
            messages.append(" ".join(entry[2:]))
        else:
            users.append('group_notification')
            messages.append(entry[0])

<>:4: SyntaxWarning: invalid escape sequence '\w'
<>:4: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_507/1015025341.py:4: SyntaxWarning: invalid escape sequence '\w'
  entry = re.split('([\w\W]+?):\s', message)

In [ ]:
df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

In [ ]:
df.head(10)

,date,user,message
0,2025-08-15 15:44:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2025-07-02 14:15:00,group_notification,"~ aqsa45476 created group ""No tension aish kro""\n"
2,2025-07-02 14:15:00,group_notification,You were added\n
3,2025-08-15 20:53:00,+92 328 2954199,This message was deleted\n
4,2025-08-15 20:55:00,Hamza Memon Uni Cf,<Media omitted>\n
5,2025-08-15 20:56:00,humbal Uni CF,Oh bhai zinda hun me czn ne kia hai story uplo...
6,2025-08-19 00:17:00,+92 302 0216782,Transcript kb tk Aaye gii\n
7,2025-08-19 00:17:00,Saher Uni CF,Jub ayegi mein Bata dongi\n
8,2025-08-19 00:17:00,+92 334 2169768,This message was deleted\n
9,2025-08-19 00:17:00,Ayan Uni Cf,<Media omitted>\n

In [ ]:
temp = df[df['user'] != 'group_notification']
temp = temp[temp['message'] != '<Media omitted>\n']

In [ ]:
f = open('stop_hinglish.txt','r')
stop_words = f.read()
print(stop_words)

.
..
...
?
-
--
1
2
3
4
5
6
7
8
9
0
a
aadi
aaj
aap
aapne
aata
aati
aaya
aaye
ab
abbe
abbey
abe
abhi
able
about
above
accha
according
accordingly
acha
achcha
across
actually
after
afterwards
again
against
agar
ain
aint
ain't
aisa
aise
aisi
alag
all
allow
allows
almost
alone
along
already
also
although
always
am
among
amongst
an
and
andar
another
any
anybody
anyhow
anyone
anything
anyway
anyways
anywhere
ap
apan
apart
apna
apnaa
apne
apni
appear
are
aren
arent
aren't
around
arre
as
aside
ask
asking
at
aur
avum
aya
aye
baad
baar
bad
bahut
bana
banae
banai
banao
banaya
banaye
banayi
banda
bande
bandi
bane
bani
bas
bata
batao
bc
be
became
because
become
becomes
becoming
been
before
beforehand
behind
being
below
beside
besides
best
better
between
beyond
bhai
bheetar
bhi
bhitar
bht
bilkul
bohot
bol
bola
bole
boli
bolo
bolta
bolte
bolti
both
brief
bro
btw
but
by
came
can
cannot
cant
can't
cause
causes
certain
certainly
chahiye
chaiye
chal
chalega
chhaiye
clearly
c'mon
com
come
comes
could
couldn
couldnt
couldn't
d
de
dede
dega
degi
dekh
dekha
dekhe
dekhi
dekho
denge
dhang
di
did
didn
didnt
didn't
dijiye
diya
diyaa
diye
diyo
do
does
doesn
doesnt
doesn't
doing
done
dono
dont
don't
doosra
doosre
down
downwards
dude
dunga
dungi
during
dusra
dusre
dusri
dvaara
dvara
dwaara
dwara
each
edu
eg
eight
either
ek
else
elsewhere
enough
etc
even
ever
every
everybody
everyone
everything
everywhere
ex
exactly
example
except
far
few
fifth
fir
first
five
followed
following
follows
for
forth
four
from
further
furthermore
gaya
gaye
gayi
get
gets
getting
ghar
given
gives
go
goes
going
gone
good
got
gotten
greetings
guys
haan
had
hadd
hadn
hadnt
hadn't
hai
hain
hamara
hamare
hamari
hamne
han
happens
har
hardly
has
hasn
hasnt
hasn't
have
haven
havent
haven't
having
he
hello
help
hence
her
here
hereafter
hereby
herein
here's
hereupon
hers
herself
he's
hi
him
himself
his
hither
hm
hmm
ho
hoga
hoge
hogi
hona
honaa
hone
honge
hongi
honi
hopefully
hota
hotaa
hote
hoti
how
howbeit
however
hoyenge
hoyengi
hu
hua
hue
huh
hui
hum
humein
humne
hun
huye
huyi
i
i'd
idk
ie
if
i'll
i'm
imo
in
inasmuch
inc
inhe
inhi
inho
inka
inkaa
inke
inki
inn
inner
inse
insofar
into
inward
is
ise
isi
iska
iskaa
iske
iski
isme
isn
isne
isnt
isn't
iss
isse
issi
isski
it
it'd
it'll
itna
itne
itni
itno
its
it's
itself
ityaadi
ityadi
i've
ja
jaa
jab
jabh
jaha
jahaan
jahan
jaisa
jaise
jaisi
jata
jayega
jidhar
jin
jinhe
jinhi
jinho
jinhone
jinka
jinke
jinki
jinn
jis
jise
jiska
jiske
jiski
jisme
jiss
jisse
jitna
jitne
jitni
jo
just
jyaada
jyada
k
ka
kaafi
kab
kabhi
kafi
kaha
kahaa
kahaan
kahan
kahi
kahin
kahte
kaisa
kaise
kaisi
kal
kam
kar
kara
kare
karega
karegi
karen
karenge
kari
karke
karna
karne
karni
karo
karta
karte
karti
karu
karun
karunga
karungi
kaun
kaunsa
kayi
kch
ke
keep
keeps
keh
kehte
kept
khud
ki
kin
kine
kinhe
kinho
kinka
kinke
kinki
kinko
kinn
kino
kis
kise
kisi
kiska
kiske
kiski
kisko
kisliye
kisne
kitna
kitne
kitni
kitno
kiya
kiye
know
known
knows
ko
koi
kon
konsa
koyi
krna
krne
kuch
kuchch
kuchh
kul
kull
kya
kyaa
kyu
kyuki
kyun
kyunki
lagta
lagte
lagti
last
lately
later
le
least
lekar
lekin
less
lest
let
let's
li
like
liked
likely
little
liya
liye
ll
lo
log
logon
lol
look
looking
looks
ltd
lunga
m
maan
maana
maane
maani
maano
magar
mai
main
maine
mainly
mana
mane
mani
mano
many
mat
may
maybe
me
mean
meanwhile
mein
mera
mere
merely
meri
might
mightn
mightnt
mightn't
mil
mjhe
more
moreover
most
mostly
much
mujhe
must
mustn
mustnt
mustn't
my
myself
na
naa
naah
nahi
nahin
nai
name
namely
nd
ne
near
nearly
necessary
neeche
need
needn
neednt
needn't
needs
neither
never
nevertheless
new
next
nhi
nine
no
nobody
non
none
noone
nope
nor
normally
not
nothing
novel
now
nowhere
o
obviously
of
off
often
oh
ok
okay
old
on
once
one
ones
only
onto
or
other
others
otherwise
ought
our
ours
ourselves
out
outside
over
overall
own
par
pata
pe
pehla
pehle
pehli
people
per
perhaps
phla
phle
phli
placed
please
plus
poora
poori
provides
pura
puri
q
que
quite
raha
rahaa
rahe
rahi
rakh
rakha
rakhe
rakhen
rakhi
rakho
rather
re
really
reasonably
regarding
regardless
regards
rehte
rha
rhaa
rhe
rhi
ri
right
s
sa
saara
saare
saath
sab
sabhi
sabse
sahi
said
sakta
saktaa
sakte
sakti
same
sang
sara
sath
saw
say
saying
says
se
second
secondly
see
seeing
seem
seemed
seeming
seems
seen
self
selves
sensible
sent
serious
seriously
seven
several
shall
shan
shant
shan't
she
she's
should
shouldn
shouldnt
shouldn't
should've
si
sir
sir.
since
six
so
soch
some
somebody
somehow
someone
something
sometime
sometimes
somewhat
somewhere
soon
still
sub
such
sup
sure
t
tab
tabh
tak
take
taken
tarah
teen
teeno
teesra
teesre
teesri
tell
tends
tera
tere
teri
th
tha
than
thank
thanks
thanx
that
that'll
thats
that's
the
theek
their
theirs
them
themselves
then
thence
there
thereafter
thereby
therefore
therein
theres
there's
thereupon
these
they
they'd
they'll
they're
they've
thi
thik
thing
think
thinking
third
this
tho
thoda
thodi
thorough
thoroughly
those
though
thought
three
through
throughout
thru
thus
tjhe
to
together
toh
too
took
toward
towards
tried
tries
true
truly
try
trying
tu
tujhe
tum
tumhara
tumhare
tumhari
tune
twice
two
um
umm
un
under
unhe
unhi
unho
unhone
unka
unkaa
unke
unki
unko
unless
unlikely
unn
unse
until
unto
up
upar
upon
us
use
used
useful
uses
usi
using
uska
uske
usne
uss
usse
ussi
usually
vaala
vaale
vaali
vahaan
vahan
vahi
vahin
vaisa
vaise
vaisi
vala
vale
vali
various
ve
very
via
viz
vo
waala
waale
waali
wagaira
wagairah
wagerah
waha
wahaan
wahan
wahi
wahin
waisa
waise
waisi
wala
wale
wali
want
wants
was
wasn
wasnt
wasn't
way
we
we'd
well
we'll
went
were
we're
weren
werent
weren't
we've
what
whatever
what's
when
whence
whenever
where
whereafter
whereas
whereby
wherein
where's
whereupon
wherever
whether
which
while
who
whoever
whole
whom
who's
whose
why
will
willing
with
within
without
wo
woh
wohi
won
wont
won't
would
wouldn
wouldnt
wouldn't
y
ya
yadi
yah
yaha
yahaan
yahan
yahi
yahin
ye
yeah
yeh
yehi
yes
yet
you
you'd
you'll
your
you're
yours
yourself
yourselves
you've
yup

In [ ]:
words = []
for message in temp['message']:
    for word in message.lower().split():
        if word not in stop_words:
            words.append(word)

In [ ]:
from collections import Counter
pd.DataFrame(Counter(words).most_common(20))

          0    1
0   message  698
1        hn  681
2     class  486
3   deleted  459
4       uni  433
5         😂  405
6       kia  365
7      miss  346
8       cf⁩  337
9       lab  282
10    <this  186
11  edited>  186
12       sb  170
13    group  167
14       a)  146
15       b)  146
16       c)  143
17    memon  135
18       d)  131
19      kro  130

In [ ]:
!pip install emoji
import emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 8.7 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [ ]:
emojis = []
for message in temp['message']:
  emojis.extend([c for c in message if emoji.is_emoji(c)])

In [ ]:
pd.DataFrame(Counter(emojis).most_common(len(Counter(emojis))))

     0    1
0    😂  806
1    🤣  618
2    😭  150
3    🥲  118
4    🙂  117
..  ..  ...
228  🤯    1
229  📧    1
230  💬    1
231  💤    1
232  😴    1

[233 rows x 2 columns]

In [ ]:
df['month_num'] = df['date'].dt.month

In [ ]:
df

,date,user,message,month_num
0,2025-08-15 15:44:00,group_notification,Messages and calls are end-to-end encrypted. O...,8
1,2025-07-02 14:15:00,group_notification,"~ aqsa45476 created group ""No tension aish kro""\n",7
2,2025-07-02 14:15:00,group_notification,You were added\n,7
3,2025-08-15 20:53:00,+92 328 2954199,This message was deleted\n,8
4,2025-08-15 20:55:00,Hamza Memon Uni Cf,<Media omitted>\n,8
...,...,...,...,...
13472,2026-03-19 13:25:00,+92 334 2169768,<Media omitted>\n,3
13473,2026-03-19 13:27:00,+92 312 1154543,Ap logon kai net issue ki waja c class cancel ...,3
13474,2026-03-19 13:27:00,+92 312 1154543,Aur next friday ko 2 c 3 lab ek sth hon gi\n,3
13475,2026-03-19 13:49:00,Mubeen Uni CF,Information security miss aqsa ki class ho gi?\n,3
13476,2026-03-19 14:21:00,+92 334 2169768,lol 😂\n,3

In [ ]:
df['only_date'] = df['date'].dt.date
df['year'] = df['date'].dt.year
df['month_num'] = df['date'].dt.month
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['day_name'] = df['date'].dt.day_name()
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute

In [ ]:
df.head()

,date,user,message,month_num,only_date,year,month,day,day_name,hour,minute
0,2025-08-15 15:44:00,group_notification,Messages and calls are end-to-end encrypted. O...,8,2025-08-15,2025,August,15,Friday,15,44
1,2025-07-02 14:15:00,group_notification,"~ aqsa45476 created group ""No tension aish kro""\n",7,2025-07-02,2025,July,2,Wednesday,14,15
2,2025-07-02 14:15:00,group_notification,You were added\n,7,2025-07-02,2025,July,2,Wednesday,14,15
3,2025-08-15 20:53:00,+92 328 2954199,This message was deleted\n,8,2025-08-15,2025,August,15,Friday,20,53
4,2025-08-15 20:55:00,Hamza Memon Uni Cf,<Media omitted>\n,8,2025-08-15,2025,August,15,Friday,20,55

In [ ]:
timeline = df.groupby(['year', 'month_num', 'month']).count()['message'].reset_index()

In [ ]:
timeline

   year  month_num      month  message
0  2025          7       July        2
1  2025          8     August      610
2  2025          9  September     3098
3  2025         10    October     2089
4  2025         11   November     1243
5  2025         12   December     1973
6  2026          1    January     1818
7  2026          2   February      716
8  2026          3      March     1928

In [ ]:
time = []
for i in range(timeline.shape[0]):
    time.append(timeline['month'][i] + "-" + str(timeline['year'][i]))

In [ ]:
time

['July-2025',
 'August-2025',
 'September-2025',
 'October-2025',
 'November-2025',
 'December-2025',
 'January-2026',
 'February-2026',
 'March-2026']

In [ ]:
timeline['time'] = time

In [ ]:
timeline

   year  month_num      month  message            time
0  2025          7       July        2       July-2025
1  2025          8     August      610     August-2025
2  2025          9  September     3098  September-2025
3  2025         10    October     2089    October-2025
4  2025         11   November     1243   November-2025
5  2025         12   December     1973   December-2025
6  2026          1    January     1818    January-2026
7  2026          2   February      716   February-2026
8  2026          3      March     1928      March-2026